backend:
  name: git-gateway
  branch: master

media_folder: app/static/img
public_folder: /img

collections:
  - name: 'articles'
    label: 'Articles'
    format: 'frontmatter'
    folder: 'app/content/articles'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: false }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Category', name: 'category', widget: 'string', required: false, default: 'ETC' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, default: [] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
